version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel/otel-config.yaml:/etc/otel/config.yaml
    command: ["--config", "/etc/otel/config.yaml"]
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8000:8000" # log
      - "55681:55681" # OpenCensus
      - "9464:9464" # Prometheus metrics
    depends_on:
      - jaeger
    networks:
      - otel-network
  jaeger:
      # image: jaegertracing/all-in-one:1.6.0
      image: jaegertracing/jaeger:2.3.0
      container_name: jaeger
      environment:
        - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      ports:
      - "16686:16686"
      - "9411:9411"
      - "5778:5778"
      # - "4317:4317"
      # - "4318:4318"
      # ports:
      #   - "5775:5775"
      #   - "4318:4318"
      #   - "4318:6832"
      #   - "5778:5778"
      #   - "16686:16686"
      networks:
        - otel-network
  demo-app:
    build: ./demo-app/.
    container_name: demo-app
    environment:
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317/v1/traces
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=demo-app
      - OTEL_SERVICE_NAME=demo-app
    ports:
      - "3000:5000"
    depends_on:
      - otel-collector
    networks:
      - otel-network
networks:
  otel-network:
    driver: bridge
    